appkings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('a-s/', admin.site.urls),
    path('', include('core.urls')),
    path('careers/', include('careers.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Appkings Solutions Admin'
admin.site.site_title = 'Appkings Solutions Admin Pannel'

careers/urls.py
from . import views
from django.urls import path

app_name = 'careers'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/', views.details, name='detail'),
]

core/urls.py
from core.views import services, base, products, blog
from . import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', base.index, name='index'),
    path('about/', base.about, name='about'),
    path('awards/', base.awards, name='awards'),
    path('contact/', base.contact, name='contact'),
    path('survey/', base.survey, name='survey'),
    path('services/', services.index, name='services'),
    path('services/<slug:slug>/', services.detail, name='service_detail'),
    path('products/', products.index, name='products'),
    path('products/tags/<slug:tag_slug>/', products.index, name='products_by_tag'),
    path('products/<slug:slug>/', products.detail, name='product_detail'),
    path('teams/', base.team, name='team'),
    path('gallery/', base.gallery, name='gallery'),
    path('search/', base.search, name='search'),
    path('faqs/', base.faq, name='faqs'),
    path('blog/', blog.index, name='blog'),
    path('blog/tags/<slug:tag_slug>/', blog.index, name='blogs_by_tag'),
    path('blog/<slug:slug>/', blog.detail, name='blog_detail'),
]

templates/partials/css.html
<link href="/static/favicon.ico" rel="icon" />
<link rel="preconnect" href="https://fonts.gstatic.com/" />
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&amp;display=swap" rel="stylesheet" />

<link href="/static/css/vendor.min.css" rel="stylesheet" />
<link href="/static/css/style.css" rel="stylesheet" />
<link href="/static/css/custom.css" rel="stylesheet" />

templates/partials/footer.html
<footer class="footer footer-1">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-6 col-md-6 col-lg-2">
                    <div class="footer-widget widget-links">
                        <div class="footer-widget-title">
                            <h5>Quick Links</h5>
                        </div>
                        <div class="widget-content">
                            <ul>
                                <li><a href="{% url 'core:about' %}">About Us</a></li>
                                <li><a href="{% url 'core:products' %}">Our Products</a></li>
                                <li><a href="{% url 'core:products' %}">Our Solutions</a></li>
                                <li><a href="{% url 'core:blog' %}">Blog</a></li>
                                <li><a href="{% url 'core:survey' %}">survey</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% if services %}
                <!--  End .col-lg-2-->
                <div class="col-12 col-sm-6 col-md-6 col-lg-2">
                    <div class="footer-widget widget-links">
                        <div class="footer-widget-title">
                            <h5>Our Solutions</h5>
                        </div>
                        <div class="widget-content">
                            <ul>
                                {% for service in services %}
                                    <li><a href="{{ service.get_absolute_url }}" title="{{ service.title }}">{{ service.title|truncatechars:27 }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% if products %}
                <!--  End .col-lg-2-->
                <div class="col-12 col-sm-6 col-md-6 col-lg-5">
                    <div class="footer-widget widget-links widget-icon">
                        <div class="footer-widget-title">
                            <h5>Our Products</h5>
                        </div>
                        <div class="widget-content">
                            <ul>
                                {% for product in products %}
                                    <li><a href="{{ product.get_absolute_url }}" title="{{ product.title }}">{{ product.title|truncatechars:27 }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!--  End .col-lg-5-->
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="footer-widget widget-links">
                        <!-- <div class="footer-widget-title">
                            <h5>Contact Us</h5>
                        </div> -->
                        <div class="widget-content">
                            <ul>
                                <li><a href="{% url 'core:contact' %}">contact us</a></li>
                                <li class="">Phone: <a href="tel:+254700191991">+254700191991</a></li>
                                <li class="">Email: <a href="mailto:info@appkings.co.ke" class="text-lowercase">info@appkings.co.ke</a>
                                </li>
                                <li class="address">
                                    <p>G1-G4, Top Plaza Building, Kindaruma Road, Off Ngong Road,
                                    </p>
                                </li>
                                <li class="directions"><a href="https://maps.app.goo.gl/Hh97P6RWPkb17RSA7"><i class="energia-location-Icon me-2"></i>get directions</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--  End .col-lg-3-->
            </div>
            <!-- End .row-->
        </div>
        <!--  End .container-->
    </div>
    <!--  End .footer-top-->
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-copyright">
                        <div class="copyright">
                            <span>&copy; <script>document.write(new Date().getFullYear());</script> <a href="/">Appkings Solutions</a>. all rights reserved.</span>
                            <ul class="list-unstyled social-icons">
                                <li><a href="{% url 'careers:index' %}">Careers</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--  End .row-->
    </div>
    <!--  End .footer-bottom-->
</footer>

templates/partials/hero-section.html
<!-- PageTitle Section-->
<section class="page-title page-title-14" id="page-title">
    <div class="page-title-wrap bg-overlay bg-overlay-dark-3">
        <div class="bg-section"><img src="{% if hero_url %}{{hero_url }}{% else %}/static/images/page-titles/1.jpg{% endif %}" alt="Background" /></div>
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="title">
                        <h3 style="font-size: 36px;" class="title-heading">{{ title|default:'Appkings Solution' }}</h3>
                        <ol class="breadcrumb breadcrumb-light">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            {% if category %}
                                <li class="breadcrumb-item"><a href="{{ category_url }}">{{ category }}</a></li>
                            {% endif %}
                            <li class="breadcrumb-item active" aria-current="page">{{ title|default:'Appkings Solution' }}</li>
                        </ol>
                        <!-- End .breadcrumb-->
                    </div>
                    <!-- End .title-->
                </div>
                <!-- End .col-12-->
            </div>
            <!-- End .row-->
        </div>
        <!-- End .container-->
    </div>
</section>

templates/partials/js.html
<script src="/static/js/vendor/jquery-3.6.0.min.js"></script>
<script src="/static/js/vendor.js"></script>
<script src="/static/js/functions.js"></script>

templates/partials/top-nav.html
<header class="header header-light header-topbar header-topbar1 header-shadow" id="navbar-spy">
    <div class="top-bar">
        <div class="block-left">
            <div class="top-contact">
                <div class="contact-infos"><i class="energia-phone-Icon text-white"></i>
                    <div class="contact-body">
                        <p><a href="tel:+254700191991">+254700191991</a></p>
                    </div>
                </div>
                <div class="contact-infos"><i class="energia-email--icon text-white"></i>
                    <div class="contact-body">
                        <p><a href="mailto:info@appkings.co.ke" class="text-lowercase">info@appkings.co.ke </a></p>
                    </div>
                </div>
                <div class="contact-infos"><i class="energia-clock-Icon text-white"></i>
                    <div class="contact-body">
                        <p>hours: Mon-Fri: 8am – 5pm </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-right">
            <!-- Start .social-links-->
            <div class="social-links">
                <a class="share-facebook text-white" href="https://web.facebook.com/appkingsSolutionsLtd/" target="_blank"><i class="energia-facebook"></i></a>
                <a class="share-instagram text-white" href="https://twitter.com/appkingss" target="_blank">
                    <img src="/static/images/icons/x.svg.webp" class="img-fluid energia-twitter bg-white rounded rounded-circle p-1" width="23" alt="X-Logo">
                </a>
                <a class="share-twitter text-white" href="" target="_blank"><i class="energia-youtube"></i></a>
            </div>
            <!-- End .social-links-->
            <div class="topbar-links">
                <a>ISO Certified - 9001:2015</a>
                <a href="https://support.appkings.co.ke">support</a>
                <a href="{% url 'core:survey' %}">Survey</a>
                <a href="{% url 'core:faqs' %}">FAQs</a>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-sticky" id="primary-menu"><a class="navbar-brand"
            href="/"><img class="logo logo-dark" src="/static/images/logo/logo-dark.png"
                alt="Energia Logo" /><img class="logo logo-mobile" src="/static/images/logo/logo-mobile.png"
                alt="Energia Logo" /></a>
        <div class="module-holder module-holder-phone">
            <div class="module module-search">
                <div class="module-icon module-icon-search"><i class="energia-search-Icon"></i></div>
            </div>
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        </div>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active" data-hover=""><a href="/" class="active"><span>Home</span></a></li>
                <li class="nav-item has-dropdown" data-hover=""><a class="dropdown-toggle" href="#"
                        data-toggle="dropdown"><span>About</span></a>
                    <ul class="dropdown-menu">
                        <li class="nav-item"><a href="{% url 'core:about' %}"><span>About us</span></a></li>
                        <li class="nav-item"><a href="{% url 'core:awards' %}"><span>Awards & recognition</span></a></li>
                        <li class="nav-item"><a href="{% url 'core:services' %}"><span>Services</span></a></li>
                        <li class="nav-item"><a href="{% url 'core:faqs' %}"><span>FAQs</span></a></li>
                    </ul>
                </li>
                {% if services %}
                <li class="nav-item has-dropdown" id="departments" data-hover=""><a class="dropdown-toggle" href="#" data-toggle="dropdown"><span>Solutions</span></a>
                    <ul class="dropdown-menu">
                        {% for service in services %}
                            <li class="nav-item"><a href="{{ service.get_absolute_url }}"><span>{{ service.title|truncatechars:45 }}</span></a></li>
                        {% endfor %}
                        <li class="nav-item"><a href="{% url 'core:services' %}"><span>View all</span></a></li>
                    </ul>
                </li>
                {% endif %}
                {% if products %}
                <li class="nav-item has-dropdown" data-hover=""><a href="{% url 'core:products' %}" class="dropdown-toggle" data-toggle="dropdown"><span>Products</span></a>
                    <ul class="dropdown-menu">
                        {% for product in products %}
                            <li class="nav-item"><a href="{{ product.get_absolute_url }}"><span>{{ product.title|truncatechars:45 }}</span></a></li>
                        {% endfor %}
                        <li class="nav-item"><a href="{% url 'core:products' %}"><span>View all</span></a></li>
                    </ul>
                </li>
                {% endif %}
                <li class="nav-item" id="contact" data-hover=""><a href="{% url 'core:blog' %}"><span>Blog</span></a></li>
                {% if gallery %}
                    <li class="nav-item" id="contact" data-hover=""><a href="{% url 'core:gallery' %}"><span>Our Gallery</span></a></li>
                {% endif %}
                {% if team_s %}
                    <li class="nav-item" id="contact" data-hover=""><a href="{% url 'core:team' %}"><span>Our Team</span></a></li>
                {% endif %}
                <li class="nav-item" id="contact" data-hover=""><a href="{% url 'core:contact' %}"><span>Let's Talk</span></a></li>
            </ul>
            <div class="module-holder">
                <div class="module module-search">
                    <div class="module-icon module-icon-search"><i class="energia-search-Icon"></i></div>
                </div>
                <div class="module module-cart">
                    <div class="module-icon module-icon-cart"><a href="tel:+254700191991"><i class="fas fa-headset"></i></a><span
                            class="title">24/7 Support</span>
                    </div>
                </div>
                <div class="module-contact"><a class="btn btn--primary " href="{% url 'core:contact' %}">
                        request a quote<i class="energia-arrow-right"></i></a></div>
            </div>
            <!--  End .module-holder-->
        </div>
        <!--  End .navbar-collapse-->
    </nav>
    <!--  End .navbar-->
</header>