appkings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('a-s/', admin.site.urls),
    path('', include('core.urls')),
    path('careers/', include('careers.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Appkings Solutions Admin'
admin.site.site_title = 'Appkings Solutions Admin Pannel'

core/urls.py
from core.views import services, base, products, blog
from . import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path('', base.index, name='index'),
    path('about/', base.about, name='about'),
    path('awards/', base.awards, name='awards'),
    path('contact/', base.contact, name='contact'),
    path('survey/', base.survey, name='survey'),
    path('services/', services.index, name='services'),
    path('services/<slug:slug>/', services.detail, name='service_detail'),
    path('products/', products.index, name='products'),
    path('products/tags/<slug:tag_slug>/', products.index, name='products_by_tag'),
    path('products/<slug:slug>/', products.detail, name='product_detail'),
    path('teams/', base.team, name='team'),
    path('gallery/', base.gallery, name='gallery'),
    path('search/', base.search, name='search'),
    path('faqs/', base.faq, name='faqs'),
    path('blog/', blog.index, name='blog'),
    path('blog/tags/<slug:tag_slug>/', blog.index, name='blogs_by_tag'),
    path('blog/<slug:slug>/', blog.detail, name='blog_detail'),
]

core/views/base.py
from django.shortcuts import render, redirect
from ..models import FAQ, Client, Review, Award, GalleryImage, Gallery, Team, Blog, Product, Service
from ..forms import ContactForm, SurveyForm
from django.contrib import messages
from django.http import Http404

def index(request):
    context = {
        'title': 'Homepage',
        'clients': Client.objects.filter(is_active=True),
        'reviews': Review.objects.filter(is_active=True)[:3]
    }
    return render(request, 'index.html', context)

def about(request):
    context = {
        'title': 'About Us',
        'clients': Client.objects.filter(is_active=True)
    }
    return render(request, 'about.html', context)

def contact(request):
    if request.method == 'POST':
        try:
            form = ContactForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Form submitted successfully.')
                return redirect('core:index')
        except Exception as e:
            messages.success(request, f'Error:{e}.')
            return redirect('core:contact')
    else:
        form = ContactForm()

    context = {
        'title': 'Contact Us',
        'reviews': Review.objects.filter(is_active=True),
        'form': form
    }
    return render(request, 'contact.html', context)

def awards(request):
    context = {
        'title': 'Awards & Recognition',
        'faqs': FAQ.objects.filter(is_active=True)[:3],
        'awards': Award.objects.filter(is_active=True),
    }
    return render(request, 'awards.html', context)

def survey(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Feedback Submitted successfully')
            return redirect('core:index')
        else:
            error_messages = form.errors.as_text()
            messages.warning(request, f'Form validation failed: \n{error_messages}')
            return redirect('core:survey')
    else:
        form = SurveyForm()

    context = {
        'title': 'Survey',
        'form': form
    }
    return render(request, 'survey.html', context)

def faq(request):
    context = {
        'title': 'Frequently Asked Questions',
        'faqs': FAQ.objects.filter(is_active=True),
    }
    return render(request, 'faqs.html', context)

def team(request):
    teams = Team.objects.filter(is_active=True)
    if not teams:
        raise Http404
    
    context = {
        'title': 'Our Team',
        'teams': teams

    }
    return render(request, 'team.html', context)

def gallery(request):
    if not Gallery.objects.filter(is_active=True).first():
        raise Http404

    context = {
        'title': 'Our Gallery',
        'images': GalleryImage.objects.filter(is_active=True)
    }
    return render(request, 'gallery.html', context)

def search(request):
    title = 'Search ...'
    services = blogs = teams = clients = products = awards = faqs = None
    query = request.GET.get('q')

    if query:
        title = f"Results for '{query}'"
        services = Service.objects.filter(title__icontains=query, is_active=True) or Service.objects.filter(description__icontains=query, is_active=True)
        blogs = Blog.objects.filter(title__icontains=query, is_published=True) or Blog.objects.filter(description__icontains=query, is_published=True)
        teams = Team.objects.filter(user__first_name__icontains=query, is_active=True) or Team.objects.filter(user__last_name__icontains=query, is_active=True) or Team.objects.filter(position__icontains=query, is_active=True)
        clients = Client.objects.filter(title__icontains=query, is_active=True)
        products = Product.objects.filter(title__icontains=query, is_active=True) or Product.objects.filter(description__icontains=query, is_active=True)
        awards = Award.objects.filter(title__icontains=query)
        faqs = FAQ.objects.filter(question__icontains=query)

    context = {
        'title': title,
        'services': services,
        'blogs': blogs,
        'teams': teams,
        'clients': clients,
        'products': products,
        'awards': awards,
        'faqs': faqs,
    }

    return render(request, 'search.html', context)

templates/about.html
{% extends 'base.html' %}
{% block content %}
  {% include 'sections/about.html' %}
  {% include 'sections/features.html' %}
  {% include 'sections/products.html' %}
  {% include 'sections/clients.html' %}
  {% include 'sections/blog.html' %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="Jeff Odhiambo, VSTech Limited" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    {% block meta %} {% endblock %}
    <title>{% block title %} {% endblock %} {% if title %}{{ title }} - {% endif %}{% if category %}{{ category }} -{% endif %} Appkings Solutions</title>
    {% include 'partials/css.html' %}
</head>

<body>
    <!-- <div class="preloader">
        <div class="dual-ring"></div>
    </div> -->

    <div class="wrapper clearfix" id="wrapperParallax">

        {% include 'partials/top-nav.html' %}

        <div class="module-content module-search-warp">
            <div class="pos-vertical-center">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-8 offset-lg-2">
                            <form class="form-search" action="{% url 'core:search' %}">
                                <input class="form-control" type="search" name="q" placeholder="Search our database ..." />
                                <button></button>
                            </form>
                            <!-- End .form-search -->
                        </div>
                        <!-- End .col-lg-8 -->
                    </div>
                    <!--  End .row-->
                </div>
                <!--  End .container-->
            </div><a class="module-cancel" href="#"><i class="fas fa-times"></i></a>
            <!-- End .module-cancel-->
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% if title != 'Homepage' and title != 'Contact Us' %}
            {% include 'partials/hero-section.html' %}
        {% endif %}
        {% block content %}

        {% endblock %}

        {% include 'partials/footer.html' %}

        <div class="back-top" id="back-to-top" data-hover=""><i class="energia-arrow-up"></i></div>
    </div>

    {% include 'partials/js.html' %}
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
      <!-- Google Map Section-->
      <section class="map map-2"> 
        <div class="container">
          <div class="row">
            <div class="col">
              <h3 class="d-none">{{ title }}</h3>
            </div>
          </div>
        </div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.795729630171!2d36.790660375778835!3d-1.2972427986904271!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f17673b747241%3A0xc242ada145328ad1!2sAppKings%20Solutions%20Ltd.!5e0!3m2!1sen!2ske!4v1703949464989!5m2!1sen!2ske" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </section>

      <!-- Testimonials Section-->
      <section class="testimonial testimonial-5 bg-overlay bg-overlay-white2">
        <div class="bg-section"><img src="/static/images/background/wavy-pattern.png" alt="background"/></div>
        <div class="container">
          <div class="contact-panel contact-panel-2">
            <div class="row">
              <div class="col-12 col-lg-5 img-card-holder">
                <div class="img-card img-card-2 bg-overlay bg-overlay-theme">
                  <div class="bg-section"><img src="/static/images/about/1.jpg" alt="image"/></div>
                  <div class="card-content">
                    <div class="content-top">
                      <p>If you have any inquiries or need assistance, Contact us today, and let's unlock the full potential of your business together.</p>
                      <a href="https://maps.app.goo.gl/Hh97P6RWPkb17RSA7" target="_blank"><i class="energia-arrow-right"></i>Visit Our Office in Person</a>
                    </div>                                                  
                    <div class="content-bottom">
                      <ul class="list-unstyled contact-infos"> 
                        <li class="contact-info"><i class="energia-phone-Icon"></i>
                          <p>Phone: <a href="tel:+254700191991">+254700191991</a></p>
                        </li>
                        <li class="contact-info"><i class="fa fa-envelope" aria-hidden="true"></i>
                          <p>Email: <a href="mailto:info@appkings.co.ke">info@appkings.co.ke</a></p>
                        </li>
                        <li class="contact-info"><i class="energia-location-Icon"></i>
                          <p>Location: <a href="https://maps.app.goo.gl/Hh97P6RWPkb17RSA7">G1-G4, Top Plaza Building, Kindaruma Road, Off Ngong Road,</a></p>
                        </li>
                        <li class="contact-info"><i class="energia-clock-Icon"></i>
                          <p>Mon - Fri: 8:00 am - 5:00 pm	</p>
                        </li>
                      </ul><a class="btn btn--white" href="{% url 'core:about' %}">About us <i class="energia-arrow-right"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12 col-lg-7">
                <div class="contact-card">
                  <div class="contact-body">
                    <h5 class="card-heading">Get in Touch</h5>
                    <p class="card-desc">At AppKings Solutions, we take pride in delivering top-quality service. Contact us today to experience excellence firsthand.</p>
                    <form method="post" action="">
                      {% csrf_token %}
                      <div class="row">
                        <div class="col-12 col-md-6">
                          {{ form.name }}
                        </div>
                        <div class="col-12 col-md-6">
                          {{ form.subject }}
                        </div>
                        <div class="col-12 col-md-6">
                          {{ form.email }}
                        </div>
                        <div class="col-12 col-md-6">
                          {{ form.phone_number }}
                        </div>
                        <div class="col-12">
                          {{ form.message }}
                        </div>
                        <div class="col-12">
                          <button type="submit" class="btn btn--secondary">submit request <i class="energia-arrow-right"></i></button>
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- End .contact-body -->
                </div>
              </div>
            </div>
            <!-- End .row-->
          </div>
          {% if reviews %}
          <!-- End .contact-panel-->
          <div class="row">
            <div class="col-12 col-lg-4">
              <div class="counters-holder"> 
                <!-- Start .counter-->
                <div class="counter counter-3">
                  <div class="counter-holder">
                    <div class="counter-num"> <span class="counting" data-counterup-nums="8" data-counterup-beginat="0">8</span></div>
                    <div class="counter-img">
                      <div class="bg-section"><img src="/static/images/sliders/1.jpg" alt="image"/></div>
                      <img src="/static/icons/rating.png" alt="">
                    </div>
                  </div>
                  <div class="counter-desc">
                    <p>Years Of Experience In The Industry</p>
                  </div>
                </div>
                <!-- End .counter-->
              </div>
            </div>
            <div class="col-12 col-lg-7 offset-lg-1">
              <div class="heading heading-14"> 
                <p class="heading-subtitle">What our clients say!</p>
              </div>
              <div class="testimonials-holder"> 
                <div class="carousel owl-carousel testimonials-carousel" data-slide="1" data-slide-rs="1" data-autoplay="true" data-nav="false" data-dots="false" data-space="0" data-loop="false" data-speed="800">
                  {% for review in reviews %}
                  <div class="testimonial-panel testimonial-panel-2">
                    <div class="testimonial-body">
                      <div class="testimonial-content">
                        <p>{{ review.message|truncatechars:240 }}</p>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
              <div class="testimonial-thumbs">
                {% for review in reviews %}
                <div class="testimonial-thumb {% if forloop.counter == 1 %}active{% endif %}" data-hover="">
                  <div class="thumb-img"> <img src="{% if review.image %}{{ review.image.url }}{% else %}/static/images/favicon/favicon.jpeg{% endif %}" alt="{{ review.name }}"/></div>
                  <div class="thumb-body"> 
                    <h6>{{ review.name }}</h6>
                    <p>{{ review.position }}</p>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% endif %}
          <!-- End .row-->
        </div>
        <!-- End .container-->
      </section>
{% endblock %}

templates/faqs.html
{% extends 'base.html' %}
{% block content %}
      <!-- Faqs Section-->
      <section class="faqs faqs-2" id="faqs-1">
        <div class="container">
          <div class="row"> 
            <div class="col-12 col-lg-6 offset-lg-3"> 
              <div class="heading heading-18 text-center">
                <p class="heading-subtitle">What Are You Looking For?</p>
                <h2 class="heading-title">Frequently Asked Questions</h2>
              </div>
            </div>
          </div>
          <div class="accordion accordion-2" id="accordion03">
            <div class="row">
              {% if faqs %}
              {% for faq in faqs %}
              <div class="col-12 col-lg-6">
                <div>
                  <div class="card">
                    <div class="card-heading"><a class="card-link collapsed" data-hover="" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapse01-{{ forloop.counter }}" href="#collapse01-{{ forloop.counter }}">{{ faq.question }}</a></div>
                    <div class="collapse" id="collapse01-{{ forloop.counter }}" data-bs-parent="#accordion03">
                      <div class="card-body">{{ faq.answer|safe }}</div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              {% else %}
                <p class="text-center">No FAQ Found</p>
              {% endif %}
          </div>
          <!-- End .row-->
        </div>
        <div class="container">
          <div class="more-faqs">
            <p>Explore our diverse range of <a href="{% url 'core:services' %}">services</a> designed to elevate your business to new heights.</p>
          </div>
        </div>
        <!-- End .container-->
      </section>
      {% include 'sections/counter.html' %}
      {% include 'sections/blog.html' %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
      <section class="slider slider-1" id="slider-1">
        <div class="container-fluid pe-0 ps-0">
          <div class="slider-carousel owl-carousel carousel-navs carousel-dots" data-slide="1" data-slide-rs="1" data-autoplay="true" data-nav="true" data-dots="true" data-space="0" data-loop="true" data-speed="800">
            <!--  Start .slide-->
            <div class="slide bg-overlay bg-overlay-dark-slider">
              <div class="bg-section"><img src="/static/images/sliders/3.jpg" alt="MIcrosoft Dynamics AX"/></div>
              <div class="container">
                <div class="row">
                  <div class="col-12 col-lg-7">
                    <div class="slide-content">
                      <h1 class="slide-headline">Microsoft<br>Dynamics AX</h1>
                      <p class="slide-desc">AppKings Solutions offers Dynamics 365 for Finance and Business Operations.</p>
                      <div class="slide-action">
                        <div class="slide-list"> 
                          <div class="icon"> <img src="/static/icons/project-management.png" alt=""></div>
                          <div class="icon"><img src="/static/icons/technology.png" alt=""></div>
                        </div><a class="btn btn--primary" href="{% url 'core:services' %}"> <span>our services</span><i class="energia-arrow-right"></i></a>
                      </div>
                    </div>
                    <!-- End .slide-content -->
                  </div>
                  <div class="col-12 col-lg-3 offset-lg-2 d-flex"> 
                    <div class="slider-panel-holder"> 
                      <div class="slider-panel">
                        <div class="icon">
                        <img src="/static/icons/technology.png" alt="" class="mb-3" width="auto">
                        </div>
                        <h5 class="panel-title">MS Dynamics AX</h5>
                        <p class="panel-desc">Dynamics 365 for Finance and Business Operations.</p><a href="{% url 'core:about' %}"><i class="energia-arrow-right"> </i></a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--  End .row-->
              </div>
              <!-- End .container-->
            </div>
            <!-- End .slide-->
            <!--  Start .slide-->
            <div class="slide bg-overlay bg-overlay-dark-slider">
              <div class="bg-section"><img src="/static/images/sliders/1.jpg" alt="Mycrosoft Dynamics 365"/></div>
              <div class="container">
                <div class="row">
                  <div class="col-12 col-lg-7">
                    <div class="slide-content">
                      <h1 class="slide-headline">Microsoft <br>Dynamics 365</h1>
                      <p class="slide-desc">AppKings Solutions brings you Microsoft Dynamics 365 expertise, delivering seamless integration, robust management, and unparalleled efficiency.</p>
                      <div class="slide-action">
                        <div class="slide-list"> 
                          <div class="icon"> <img src="/static/icons/project-management.png" alt=""></div>
                          <div class="icon"><img src="/static/icons/technology.png" alt=""></div>
                        </div><a class="btn btn--primary" href="{% url 'core:services' %}"> <span>our solutions</span><i class="energia-arrow-right"></i></a>
                      </div>
                    </div>
                    <!-- End .slide-content -->
                  </div>
                  <div class="col-12 col-lg-3 offset-lg-2 d-flex"> 
                    <div class="slider-panel-holder"> 
                      <div class="slider-panel">
                        <div class="icon">
                        <img src="/static/icons/technology.png" alt="" class="mb-3" width="auto">
                        </div>
                        <h5 class="panel-title">our mission</h5>
                        <p class="panel-desc">To Bridge the gap between modern technology and client's need.</p><a href="{% url 'core:about' %}"><i class="energia-arrow-right"> </i></a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--  End .row-->
              </div>
              <!-- End .container-->
            </div>
            <!-- End .slide-->
            <!--  Start .slide-->
            <div class="slide bg-overlay bg-overlay-dark-slider">
              <div class="bg-section"><img src="/static/images/sliders/2.jpg" alt="Business Intelligence"/></div>
              <div class="container">
                <div class="row">
                  <div class="col-12 col-lg-7">
                    <div class="slide-content">
                      <h1 class="slide-headline">Business Intelligence.</h1>
                      <p class="slide-desc">AppKings Solutions transforms your raw data into actionable insights. Navigate the complexities of your business with clarity and foresight.</p> 
                      <div class="slide-action">
                        <div class="slide-list"> 
                          <div class="icon"> <img src="/static/icons/project-management.png" alt=""></div>
                          <div class="icon"><img src="/static/icons/technology.png" alt=""></div>
                        </div><a class="btn btn--primary" href="{% url 'core:services' %}"> <span>our services</span><i class="energia-arrow-right"></i></a>
                      </div>
                    </div>
                    <!-- End .slide-content -->
                  </div>
                  <div class="col-12 col-lg-3 offset-lg-2 d-flex"> 
                    <div class="slider-panel-holder"> 
                      <div class="slider-panel">
                        <!-- <i class="panel-icon flaticon-019-electric-tower"></i> -->
                        <h5 class="panel-title">our vision</h5>
                        <p class="panel-desc">To be the leading Pan African IT Company for consulting services and Deployment of best of breed Business Solutions for domestic and international customers.</p><a href="{% url 'core:about' %}"><i class="energia-arrow-right"> </i></a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--  End .row-->
              </div>
              <!-- End .container-->
            </div>
            <!-- End .slide-->
          </div>
          <!-- End .slider-carousel-->
        </div>
        <!--  End .container-fluid-->
      </section>
      {% include 'sections/about.html' %}
      {% include 'sections/features.html' %}
      {% include 'sections/services.html' %}
      {% include 'sections/counter.html' %}
      {% if reviews %}
      <!--Testimonials Section-->
      <section class="testimonial testimonial-1 bg-theme2">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <div class="carousel owl-carousel carousel-nav carousel-dots" data-slide="2" data-slide-rs="1" data-autoplay="true" data-nav="true" data-dots="true" data-space="40" data-loop="true" data-speed="800">
                {% for review in reviews %}
                <div class="testimonial-panel">
                  <div class="testimonial-body">
                    <div class="testimonial-img"> <img src="{% if review.image %}{{ review.image.url }}{% else %}/static/images/favicon/favicon.jpeg{% endif %}" alt="{{ review.name }}"/></div>
                    <div class="testimonial-content">
                      <p><q>{{ review.message|truncatechars:120 }}</q></p>
                      <div class="testimonial-meta"> 
                        <h6>{{ review.name }}</h6>
                        <p>{{ review.position }}</p>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <!-- End .row-->
        </div>
        <!-- End .container-->
      </section>
      {% endif %}
      {% include 'sections/products.html' %}
      {% include 'sections/clients.html' %}
      {% include 'sections/blog.html' %}
{% endblock %}

templates/survey.html
{% extends 'base.html' %}
{% block content %}
      <!-- Survey Section-->
      <section class="contact contact-4" id="contact-4">
        <div class="container">
          <div class="contact-panel contact-panel-3">
            <div class="heading heading-6">
              <p class="heading-subtitle">Help Us Improve Your Experience.</p>
              <h2 class="heading-title">Share Your Insights and Shape Our Future!</h2>
              <p class="heading-desc">At AppKings Solutions, we are committed to enhancing our operations, services, and products based on your valuable feedback. Rest assured, your data will be securely guarded. We prioritize your privacy and employ advanced measures to protect your information. Your insights play a crucial role in guiding us towards continuous improvement.</p>
              <p class="heading-desc">Take a moment to share your insights through our survey. Your feedback matters as we strive for excellence in delivering the best quality service tailored to your needs.</p>
              <div class="contact-action"><a class="btn btn--primary" href="{% url 'core:about' %}">learn more <i class="energia-arrow-right"></i></a><a class="btn btn--bordered btn--white" href="{% url 'core:contact' %}">contact us</a></div>
              <div class="contact-quote contact-quote-3"> <img src="/static/icons/question.png" alt="icon"/>
                <p>Receive an accurate quote within 3-5 days when you fill out <a href="{% url 'core:contact' %}">contact us</a> form. Or, give us a call: <a href="tel:+254700191991">+254700191991</a></p>
              </div>
            </div>
            <div class="contact-card">
              <div class="contact-body">
                <form method="post" action="">
                  {% csrf_token %}
                  <div class="mb-20">
                    <div class="row">
                      <div class="col-12 col-md-6">
                        <label class="form-label" for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
                        {{ form.name }}
                      </div>
                      <div class="col-12 col-md-6">
                        <label class="form-label" for="{{ form.email.id_for_label }}">{{ form.email.label_tag }}</label>
                        {{ form.email }}
                      </div>
                      <div class="col-12 col-md-6">
                        <label class="form-label" for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label_tag }}</label>
                        {{ form.phone_number }}
                      </div>
                      <div class="col-12 col-md-6">
                        <label class="form-label" for="{{ form.discover_method.id_for_label }}">{{ form.discover_method.label_tag }}</label>
                        {{ form.discover_method }}
                      </div>
                      <div class="col-12">
                        <label class="form-label" for="{{ form.recommend_to_friends.id_for_label }}">{{ form.recommend_to_friends.label_tag }}</label>
                        {{ form.recommend_to_friends }}
                    </div>
                    </div>
                  </div>
                  <div>
                    <div class="row">
                      <div class="col-12">
                        <label class="form-label" for="{{ form.liked_about_us.id_for_label }}">{{ form.liked_about_us.label_tag }}</label>
                        {{ form.liked_about_us }}
                      </div>  
                      <div class="col-12">
                          <label class="form-label" for="{{ form.improvements_needed.id_for_label }}">{{ form.improvements_needed.label_tag }}</label>
                          {{ form.improvements_needed }}
                      </div>
                      <div class="col-12">
                          <label class="form-label" for="{{ form.additional_suggestions.id_for_label }}">{{ form.additional_suggestions.label_tag }}</label>
                          {{ form.additional_suggestions }}
                      </div>                    
                    </div>
                  </div>
                  <div> 
                    <div class="row">
                      <div class="col-12">
                        <button class="btn btn--secondary w-100">submit request <i class="energia-arrow-right"></i></button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
              <!-- End .contact-body -->
            </div>
          </div>
          <!-- End .contact-panel-->
        </div>
        <!-- End .container-->
      </section>
{% endblock %}

templates/team.html
{% extends 'base.html' %}
{% block content %}
    <!-- Team Section-->
    {% include 'sections/team.html' %}
{% endblock %}